### ISSUE TITLE
Values of the elements of Q-table

### ISSUE THREAD

**Issue by wangtingwei1993** [RjDuan/AdvDrop#11]
Hi, as you said in your paper (Section 3.4 Quantization) --- 'As the quantization table q should be integers during the optimization'. Do you think the data type of q table really affects the results? I mean what will happen if the elements in the q-table are float numbers. Thanks!

**Comment by RjDuan** [comment]
Yes, I have tried updated quantization table Q with float numbers, it requires more iterations & a High chance it will not perform a "quantization" effect.

**Comment by wangtingwei1993** [comment]
Thanks for your kind reply. your reply is really helpful.
________________________________
