### ISSUE TITLE
advdrop在cifar10上

### ISSUE THREAD

**Issue by linghuchong111da** [RjDuan/AdvDrop#15]

**Comment by linghuchong111da** [comment]
> 作者你好，我采用本方法在cifar10上做了实验，但是完全不能攻击，请问下可能是什么原因?

**Comment by RjDuan** [comment]
您好呀，如果最后attack成功率是0这样的话，
可能是中间量化-压缩环节对32*32图像没能处理好，目前默认量化单位是8*8这样的，您可以看一看调整这一部分代码会不会解决您问题。
linghuchong111da ***@***.***> 于2022年6月30日周四 14:20写道：

**Comment by chenboluo** [comment]
你好你有成功攻击吗
