### ISSUE TITLE
adversarial example

### ISSUE THREAD

**Issue by zhanghqq** [RjDuan/AdvDrop#16]
Hi, I used the dataset and code you provided to make adversarial examples. Running the program, the correct rate of the adversarial samples is 100% (q=100), but the adversarial examples are sent back to the network for classification, and half of the adversarial examples do not change the original correct classification results.I don't know if you or anyone else has this problem.

**Comment by RjDuan** [comment]
Hi, thanks for your interest.
Precision changes, when running in the program, adversaries are
calculated as float32 (may different depends on your hardware).
But if you save adversaries with other type, e.g., int16, or float16,  then
sent back, the results will change.
You may print out the type of adversaries to check the if precision of
number keep the same.

Hope the information helps.


tianxianbaoba ***@***.***> 于2022年9月15日周四 16:24写道：

**Comment by zhanghqq** [comment]
Hi, thank you very much for taking the time to answer this question. I checked the data type of the adversarial examples in the "save_img" function. The data type is float32. After that, the function converts to RGB image using uint8. I use the source code you provided and have not changed.The problem should not be the cause of the wrong save data type. So unfortunately, my ability is not enough to solve the problem of adversarial examples production failure.
`def save_img(img, img_name, save_dir):          
    create_dir(save_dir)
    img_path = os.path.join(save_dir, img_name)
    img_pil = Image.fromarray(img.astype(np.uint8))
    print(img.dtype)          #float32
    img_pil.save(img_path)`

**Comment by RjDuan** [comment]
Emmm, if you want to keep the "adversarial effect", you could save them
with ".npy" formmat.
Function save_img(.) is used to visualize the resultant images, and when
adversarial images converts to "uint8", value of images change, may lost
their adversarial effect.

tianxianbaoba ***@***.***> 于2022年9月16日周五 11:22写道：

**Comment by zhanghqq** [comment]
I tried to save an adversarial example using the "npy" method, but how do I recognize and classify it through the network? Input to the network needs to convert nparry type to tensor type, **img=Image.fromarray(np.uint8(img))**. This will inevitably change the value, which will ultimately affect the classification result. How to get npy files into the network without losing values? Can you give me some pointers? Thanks!

**Comment by RjDuan** [comment]
Hi there, as you said " Input to the network needs to convert nparry type
to tensor type", actually you do not need to convert img to np.uint8, you
can read it as ".npy" with np.load directly then feed it to the network.
May be the following link is helpful for you?
https://numpy.org/doc/stable/reference/generated/numpy.load.html


tianxianbaoba ***@***.***> 于2022年9月16日周五 18:47写道：
