### ISSUE TITLE
关于代码

### ISSUE THREAD

**Issue by cqzzg** [RjDuan/AdvDrop#2]
感觉您这篇论文也很有意思，想看一下具体地实现流程，代码和实验用的相关图片数据能不能发一下呢。邮箱：zg_1233@163.com谢谢

**Comment by RjDuan** [comment]
好的呀，非常高兴你对这个工作也感兴趣呀~今晚传数据集，不过imagenet数据集都行的，代码直接就可以用了~
要是跑起来有问题也欢迎提issue呀(◍•ᴗ•◍)

cqzzg ***@***.***> 于 2021年9月2日周四 下午4:55写道：
