### ISSUE TITLE
RuntineError: Boolean value of Tensor with nore than one value is ambiguous

### ISSUE THREAD

**Issue by chenboluo** [RjDuan/AdvDrop#20]
Hi, I found this error when I tried to run infod_sample.py：RuntineError: Boolean value of Tensor with nore than one value is ambiguous. I don't know how to fix it. Could you help me clear the above mentioned confusions. Thank you!
![image](https://user-images.githubusercontent.com/48652819/224624079-de8e717b-df02-47f5-bd95-708523f35c0c.png)

**Comment by chenboluo** [comment]
I solved this problem by modifying nn.Module

**Comment by Shinya754** [comment]
@chenboluo 
Hello, could you please explain how you specifically solved the problem? I also encountered that.

**Comment by chenboluo** [comment]
> @chenboluo Hello, could you please explain how you specifically solved the problem? I also encountered that.

![image](https://github.com/RjDuan/AdvDrop/assets/48652819/f9348dbd-73ac-4440-acc0-e5ee9bf74427)
Time has passed for some time. I don't remember it very well. I seem to have changed attack to nn.Module and that works. However, my test results on cifar10 are not satisfactory. If you test images at other scales, please discuss and communicate.
