### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by huwenfeng233** [RjDuan/AdvDrop#23]
1. 请问您训练的数据集是事先将imagenet中的jpeg格式图片转化成png格式的图片吗？
2. 论文里说摘取了2000张图像，训练的时候是只使用了这2000张图片进行训练的吗？

**Comment by RjDuan** [comment]
1. 是滴
2. 严格来说应该没有“训练”过程，是在这部分subset上做攻击测试。

胡文锋 ***@***.***> 于2024年10月23日周三 22:50写道：

**Comment by huwenfeng233** [comment]
好的，感谢
