### ISSUE TITLE
a minor bug

### ISSUE THREAD

**Issue by Shuaiwu** [RjDuan/AdvDrop#3]
An interesting work.  A minor bug was found  in the implementation of phi_diff which did not follow the equation 6 of original paper.
`
 phi_x = torch.tanh((x - (torch.floor(x) + 0.5)) * k) * s
`

**Comment by RjDuan** [comment]
Hi,
Thanks a lot for such patience on the work :D
Received with many thanks!
Will take a close look and reply to you!

Shuaiwu ***@***.***> 于2021年9月6日周一 下午3:16写道：
