### ISSUE TITLE
where is the  epsilon ?

### ISSUE THREAD

**Issue by PPPPPPPeng** [RjDuan/AdvDrop#8]
I want to know where is  the  epsilon ? Maybe in the code,the  epsilon  is  q_size?

**Comment by RjDuan** [comment]
Yes.

**Comment by HashmatShadab** [comment]
Regarding the q_size, to reproduce the results in Table 1 of the paper, should the range of q be [5, q_size]? Using targetted and untargetted attack for 500 and 50 steps respectively gives higher accuracy than what is mentioned in the table.
