### ISSUE TITLE
Question about DCT

### ISSUE THREAD

**Issue by shuangerwaiwai** [RjDuan/AdvDrop#9]
Hi, thanks for your work. It is very interesting. But I have a question about mathmatical definition of DCT in your paper:  What are the meanings of  parameters ‘u, v, k, m’ in the formula? Looking forward to your reply, thanks!!!

**Comment by RjDuan** [comment]
Hi, many thanks for your interest :)
Parameters ‘u, v, k, m’ are used during the inner transformation of DCT,
which is DCT's mechanism and not very related to AdvDrop.
Maybe the following link is helpful:
https://users.cs.cf.ac.uk/Dave.Marshall/Multimedia/node231.html


shuangerwaiwai ***@***.***> 于2021年11月2日周二 下午5:27写道：

**Comment by shuangerwaiwai** [comment]
Thank you！！！

**Comment by shuangerwaiwai** [comment]
Hi， there is another question. How do you choose low , moddle and high frequence infromation to drop?

**Comment by RjDuan** [comment]
Hi,  I do try this in the ablation study by setting values as 1 and 0 in
the corresponding region of the quantization table.
e.g. quantization table like this to only drop high-frequency information.
[1,1,1,1,0,0,0,0]
[1,1,1,0,0,0,0,0]
[1,1,0,0,0,0,0,0]
[1,0,0,0,0,0,0,0] ....
Somewhat, the region (low, middle or high) of frequency can be controlled
by quantization table, but not strict.
Actually no clear definition about where is the high-frequency region or
low-frequency region...
Maybe a good way is to set another weight matrix to control the degree of
dropping information on the different regions of the quantization table.


shuangerwaiwai ***@***.***> 于2021年11月5日周五 下午8:52写道：

**Comment by shuangerwaiwai** [comment]
Got it! Thanks for your replay :)
